VALUE_TO_FAMILY = {
    "Social Power": "Power",
    "Authority": "Power",
    "Wealth": "Power",
    "Preserving my Public Image": "Power",
    "Social Recognition": "Power",
    "Successful": "Achievement",
    "Capable": "Achievement",
    "Ambitious": "Achievement",
    "Influential": "Achievement",
    "Intelligent": "Achievement",
    "Self-Respect": "Achievement",
    "Pleasure": "Hedonism",
    "Enjoying Life": "Hedonism",
    "Daring": "Stimulation",
    "A Varied Life": "Stimulation",
    "An Exciting Life": "Stimulation",
    "Creativity": "Self-direction",
    "Curious": "Self-direction",
    "Freedom": "Self-direction",
    "Choosing Own Goals": "Self-direction",
    "Independent": "Self-direction",
    "Protecting the Environment": "Universalism",
    "A World of Beauty": "Universalism",
    "Broad-Minded": "Universalism",
    "Social Justice": "Universalism",
    "Wisdom": "Universalism",
    "Equality": "Universalism",
    "A World at Peace": "Universalism",
    "Inner Harmony": "Universalism",
    "Unity With Nature": "Universalism",
    "Helpful": "Benevolence",
    "Honest": "Benevolence",
    "Forgiving": "Benevolence",
    "Loyal": "Benevolence",
    "Responsible": "Benevolence",
    "True Friendship": "Benevolence",
    "A Spiritual Life": "Benevolence",
    "Mature Love": "Benevolence",
    "Meaning in Life": "Benevolence",
    "Devout": "Tradition",
    "Accepting my Portion in Life": "Tradition",
    "Humble": "Tradition",
    "Moderate": "Tradition",
    "Respect for Tradition": "Tradition",
    "Detachment": "Tradition",
    "Politeness": "Conformity",
    "Honoring of Parents and Elders": "Conformity",
    "Obedient": "Conformity",
    "Self-Discipline": "Conformity",
    "Clean": "Security",
    "National Security": "Security",
    "Social Order": "Security",
    "Family Security": "Security",
    "Reciprocation of Favors": "Security",
    "Healthy": "Security",
    "Sense of Belonging": "Security",
}
